"""Update DB

Revision ID: 3a8d58b7a23f
Revises: 8b2b40788588
Create Date: 2026-01-09 02:33:46.427713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8d58b7a23f'
down_revision: Union[str, None] = '8b2b40788588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('webphone_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sip_extension', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('sip_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('sip_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sip_domain', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sip_ws_server', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sip_port', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sip_protocol', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('webphone_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('webphone_process_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('webphone_agent_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('call_recording_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('call_log_enabled', sa.Boolean(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'call_log_enabled')
    op.drop_column('users', 'call_recording_enabled')
    op.drop_column('users', 'webphone_agent_id')
    op.drop_column('users', 'webphone_process_id')
    op.drop_column('users', 'webphone_api_key')
    op.drop_column('users', 'sip_protocol')
    op.drop_column('users', 'sip_port')
    op.drop_column('users', 'sip_ws_server')
    op.drop_column('users', 'sip_domain')
    op.drop_column('users', 'sip_password')
    op.drop_column('users', 'sip_username')
    op.drop_column('users', 'sip_extension')
    op.drop_column('users', 'webphone_enabled')
    op.drop_column('tenant', 'partner_id')
    # ### end Alembic commands ###
