"""Add token_version to User and create Ticket System tables

Revision ID: 53cbd4377b51
Revises: 20ec28d524c6
Create Date: 2026-01-08 03:47:13.792464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cbd4377b51'
down_revision: Union[str, None] = '20ec28d524c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('ticket_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_flows_id'), 'ticket_flows', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_flows_tenant_id'), 'ticket_flows', ['tenant_id'], unique=False)
    op.create_table('ticket_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('sla_id', sa.UUID(), nullable=True),
    sa.Column('extension_schema', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_templates_id'), 'ticket_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_templates_tenant_id'), 'ticket_templates', ['tenant_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', 'CRITICAL', name='ticketpriority'), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('sla_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['ticket_flows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['ticket_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tickets_code'), 'tickets', ['code'], unique=True)
    op.create_index(op.f('ix_tickets_created_by'), 'tickets', ['created_by'], unique=False)
    op.create_index(op.f('ix_tickets_flow_id'), 'tickets', ['flow_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_template_id'), 'tickets', ['template_id'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_table('ticket_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('context_metadata', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_contexts_context_type'), 'ticket_contexts', ['context_type'], unique=False)
    op.create_index(op.f('ix_ticket_contexts_id'), 'ticket_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_contexts_ticket_id'), 'ticket_contexts', ['ticket_id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('actor_type', sa.String(length=38), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_events_event_type'), 'ticket_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ticket_events_id'), 'ticket_events', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    op.create_table('ticket_extensions',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('ticket_flow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='flowinstancestatus'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['ticket_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_flow_instances_flow_id'), 'ticket_flow_instances', ['flow_id'], unique=False)
    op.create_index(op.f('ix_ticket_flow_instances_id'), 'ticket_flow_instances', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_flow_instances_status'), 'ticket_flow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_flow_instances_ticket_id'), 'ticket_flow_instances', ['ticket_id'], unique=False)
    op.create_table('ticket_flow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('assignee_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['ticket_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_flow_steps_assignee_group_id'), 'ticket_flow_steps', ['assignee_group_id'], unique=False)
    op.create_index(op.f('ix_ticket_flow_steps_assignee_user_id'), 'ticket_flow_steps', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_flow_steps_flow_id'), 'ticket_flow_steps', ['flow_id'], unique=False)
    op.create_index(op.f('ix_ticket_flow_steps_id'), 'ticket_flow_steps', ['id'], unique=False)
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_tags')
    op.drop_index(op.f('ix_ticket_flow_steps_id'), table_name='ticket_flow_steps')
    op.drop_index(op.f('ix_ticket_flow_steps_flow_id'), table_name='ticket_flow_steps')
    op.drop_index(op.f('ix_ticket_flow_steps_assignee_user_id'), table_name='ticket_flow_steps')
    op.drop_index(op.f('ix_ticket_flow_steps_assignee_group_id'), table_name='ticket_flow_steps')
    op.drop_table('ticket_flow_steps')
    op.drop_index(op.f('ix_ticket_flow_instances_ticket_id'), table_name='ticket_flow_instances')
    op.drop_index(op.f('ix_ticket_flow_instances_status'), table_name='ticket_flow_instances')
    op.drop_index(op.f('ix_ticket_flow_instances_id'), table_name='ticket_flow_instances')
    op.drop_index(op.f('ix_ticket_flow_instances_flow_id'), table_name='ticket_flow_instances')
    op.drop_table('ticket_flow_instances')
    op.drop_table('ticket_extensions')
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_event_type'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_ticket_contexts_ticket_id'), table_name='ticket_contexts')
    op.drop_index(op.f('ix_ticket_contexts_id'), table_name='ticket_contexts')
    op.drop_index(op.f('ix_ticket_contexts_context_type'), table_name='ticket_contexts')
    op.drop_table('ticket_contexts')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_template_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_flow_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_templates_tenant_id'), table_name='ticket_templates')
    op.drop_index(op.f('ix_ticket_templates_id'), table_name='ticket_templates')
    op.drop_table('ticket_templates')
    op.drop_index(op.f('ix_ticket_flows_tenant_id'), table_name='ticket_flows')
    op.drop_index(op.f('ix_ticket_flows_id'), table_name='ticket_flows')
    op.drop_table('ticket_flows')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
