"""update_ticket_events_actor_id_to_string

Revision ID: 5bd834f0cb38
Revises: 3a8d58b7a23f
Create Date: 2026-01-12 02:30:49.383858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd834f0cb38'
down_revision: Union[str, None] = '3a8d58b7a23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Alter actor_type from VARCHAR(38) to VARCHAR(100)
    op.alter_column('ticket_events', 'actor_type',
               existing_type=sa.VARCHAR(length=38),
               type_=sa.String(length=100),
               existing_nullable=True)
    
    # 2. Convert actor_id from UUID to String - Need to cast existing data
    # First, alter column with USING clause to cast UUID to text
    op.execute("""
        ALTER TABLE ticket_events 
        ALTER COLUMN actor_id TYPE VARCHAR(100) 
        USING actor_id::text
    """)
    
    # 3. Create indexes
    op.create_index(op.f('ix_ticket_events_actor_id'), 'ticket_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_created_at'), 'ticket_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_events_tenant_id'), 'ticket_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop indexes
    op.drop_index(op.f('ix_ticket_events_tenant_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_created_at'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_actor_id'), table_name='ticket_events')
    
    # 2. Convert actor_id back from String to UUID
    op.execute("""
        ALTER TABLE ticket_events 
        ALTER COLUMN actor_id TYPE UUID 
        USING actor_id::uuid
    """)
    
    # 3. Revert actor_type
    op.alter_column('ticket_events', 'actor_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=38),
               existing_nullable=True)
    # ### end Alembic commands ###
