"""delete relati customer

Revision ID: 7a444efcee05
Revises: c6b95695be6d
Create Date: 2026-03-04 07:20:24.920051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a444efcee05'
down_revision: Union[str, None] = 'c6b95695be6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_created_by_fkey', 'customers', type_='foreignkey')
    op.drop_constraint('customers_tenant_id_fkey', 'customers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('customers_tenant_id_fkey', 'customers', 'tenant', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('customers_created_by_fkey', 'customers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
