"""Update datetime to timezone-aware

Revision ID: 9b154fa25f6c
Revises: 5bd834f0cb38
Create Date: 2026-01-13 02:33:57.476473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b154fa25f6c'
down_revision: Union[str, None] = '5bd834f0cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
