"""Create table user_legacy_map

Revision ID: 9fcad9421693
Revises: 7a444efcee05
Create Date: 2026-03-31 09:53:55.812281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcad9421693'
down_revision: Union[str, None] = '7a444efcee05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_legacy_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chat_woot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_woot_id', name='uq_user_legacy_map_chatwoot'),
    sa.UniqueConstraint('uuid', name='uq_user_legacy_map_uuid')
    )
    op.create_index('idx_user_legacy_map_chatwoot', 'user_legacy_map', ['chat_woot_id'], unique=False)
    op.create_index('idx_user_legacy_map_uuid', 'user_legacy_map', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_legacy_map_uuid', table_name='user_legacy_map')
    op.drop_index('idx_user_legacy_map_chatwoot', table_name='user_legacy_map')
    op.drop_table('user_legacy_map')
    # ### end Alembic commands ###
