"""add agent_id to tenant

Revision ID: b1d6dfe99008
Revises: d4862819c0b8
Create Date: 2026-07-16 08:23:34.108825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d6dfe99008'
down_revision: Union[str, None] = 'd4862819c0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('agent_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'agent_id')
    # ### end Alembic commands ###
