"""add_customer_table_and_tag_type_and_tenant_metadata

Revision ID: c6b95695be6d
Revises: 9b154fa25f6c
Create Date: 2026-03-04 07:05:37.866885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6b95695be6d'
down_revision: Union[str, None] = '9b154fa25f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for PostgreSQL ENUM ###
    op.create_table(
        'customers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_customers_created_by'), 'customers', ['created_by'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)

    op.create_table(
        'customer_tags',
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('customer_id', 'tag_id'),
    )

    # Tạo PostgreSQL ENUM type cho cột tags.type
    tag_enum = postgresql.ENUM('TICKET', 'CUSTOMER', name='tagtype')
    tag_enum.create(op.get_bind(), checkfirst=True)

    # Thêm cột type, set server_default='TICKET' để đảm bảo dữ liệu cũ hợp lệ
    op.add_column(
        'tags',
        sa.Column(
            'type',
            tag_enum,
            nullable=False,
            server_default='TICKET',
        ),
    )
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)

    # Thêm cột meta_data cho tenant
    op.add_column('tenant', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for PostgreSQL ENUM ###
    op.drop_column('tenant', 'meta_data')

    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_column('tags', 'type')

    # Drop PostgreSQL ENUM type
    tag_enum = postgresql.ENUM('TICKET', 'CUSTOMER', name='tagtype')
    tag_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_table('customer_tags')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
