"""add customer_provided_info table

Revision ID: d4862819c0b8
Revises: a1b2c3d4e5f6
Create Date: 2026-06-18 09:13:04.332132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4862819c0b8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_provided_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_provided_info_email'), 'customer_provided_info', ['email'], unique=False)
    op.create_index(op.f('ix_customer_provided_info_id'), 'customer_provided_info', ['id'], unique=False)
    op.create_index(op.f('ix_customer_provided_info_phone'), 'customer_provided_info', ['phone'], unique=False)
    op.create_index(op.f('ix_customer_provided_info_tenant_id'), 'customer_provided_info', ['tenant_id'], unique=False)
    op.alter_column('chatwoot_legacy_map', 'resource_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('account', 'user', 'agent', 'agent_bot', name='chatwootmapresourcetype', native_enum=False),
               existing_nullable=False)
    op.add_column('tenant', sa.Column('graph_id', sa.UUID(), nullable=True))
    op.add_column('tenant', sa.Column('graph_activated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'graph_activated')
    op.drop_column('tenant', 'graph_id')
    op.alter_column('chatwoot_legacy_map', 'resource_type',
               existing_type=sa.Enum('account', 'user', 'agent', 'agent_bot', name='chatwootmapresourcetype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_customer_provided_info_tenant_id'), table_name='customer_provided_info')
    op.drop_index(op.f('ix_customer_provided_info_phone'), table_name='customer_provided_info')
    op.drop_index(op.f('ix_customer_provided_info_id'), table_name='customer_provided_info')
    op.drop_index(op.f('ix_customer_provided_info_email'), table_name='customer_provided_info')
    op.drop_table('customer_provided_info')
    # ### end Alembic commands ###
